### ISSUE TITLE
which version had you used of user work space(or developer workspace with webui) ? 

### ISSUE THREAD

**Issue by ratansinhparmar** [GeoSensorWebLab/kura-sensorthings-tutorial#1]
i had download user workspace3.0.0 and user workspace2.0.0 with web ui but org.eclipse.kura.api not got in them. so help me to give version of user work space.

**Comment by openfirmware** [comment]
Hello!

The tutorial uses version 1.4.0 of the user workspace.

I will update the tutorial document with more clear versions of the various libraries.
